//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCustomer()
        {
            this.TblSales = new HashSet<TblSale>();
        }
    
        public int Customerid { get; set; }

        [Required(ErrorMessage = "Customer Name can not be left blank. Please enter Customer Name")]
        [StringLength(50,ErrorMessage ="A name of up to 50 characters can be entered.")]
        public string CustomerName { get; set; }

        [Required(ErrorMessage = "Customer Surname can not be left blank. Please enter Customer SURName")]
        [StringLength(50, ErrorMessage = "A name of up to 50 characters can be entered.")]
        public string CustomerSurname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSale> TblSales { get; set; }
    }
}
