//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSale
    {
        public int Salesid { get; set; }
        public Nullable<int> SalesProduct { get; set; }
        public Nullable<int> SalesCustomer { get; set; }
        public Nullable<byte> SalesNumbers { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
    
        public virtual TblCustomer TblCustomer { get; set; }
        public virtual TblProduct TblProduct { get; set; }
    }
}
